### PR TITLE
Add helper function for step2.sh output formatting

### PR DESCRIPTION
**Pull request by aperloff**
Adds a new option to step2.sh to store the output files in a directory structure based on the era and dataset. Along with the README information this commit adds a helper function for formatting the filename.

### CODE REVIEW

**Comment by kpedro88** [comment]
actually, i think this is not general enough for this repo, it should just go in step2.sh in TreeMaker
(other users will likely have different file name patterns)

(also, nothing in this PR actually requires the use of -f, any argument could be used)

**Comment by aperloff** [comment]
Shall I just stick this bash function at the top of step2.sh and then close this PR?

**Comment by kpedro88** [comment]
Yes, please

**Comment by aperloff** [comment]
The main part of this PR, the structuredOutput function, has been moved to step2.sh in the TreeMaker repo as it was not general enough for this repo and was specialized to the TreeMaker output format.

**Pull request closed without merging**
